netguru/reminders

app/controllers/project_checks_controller.rb
app/use_cases/project_checks/override_deadline.rb
app/views/project_checks/index.slim
config/routes.rb
spec/controllers/project_checks_controller_spec.rb
spec/use_cases/project_checks/override_deadline_spec.rb

Add ability to set initial due date for newly added projects

Feature admin override initial due date

---

app/assets/javascripts/project_checks.coffee
app/assets/javascripts/projects.coffee
app/assets/stylesheets/components/_switch.scss
app/decorators/project_check_decorator.rb
app/views/project_checks/index.slim
app/views/projects/index.slim
app/views/users/index.slim
spec/decorators/project_check_decorator_spec.rb
spec/support/pages/projects/sections/project_table_row.rb
spec/support/pages/users/sections/users_table_row.rb

Add disabled tab just for disabled project checks.
Hide disabled from All/Overdue/Not checked yet tabs

Reorganize project check tabs

---

app/assets/javascripts/data_tables.coffee

Fixes JS error + the search is working

Keep default search independent from col number

---

db/seeds.rb

Add required fields to project seeds

Add required fields to project seeds

---

app/controllers/check_assignments_controller.rb
app/controllers/project_checks_controller.rb
app/mailers/user_notification_mailer.rb
app/models/check_assignment.rb
app/use_cases/check_assignments/assign_person.rb
app/use_cases/check_assignments/create.rb
app/views/user_notification_mailer/check_assignment.slim
db/migrate/20151127183800_add_contact_person_to_check_assignments.rb
db/schema.rb
spec/use_cases/check_assignments/assign_person_spec.rb
spec/use_cases/check_assignments/create_completed_spec.rb
spec/use_cases/check_assignments/create_spec.rb
spec/use_cases/check_assignments/resolve_action_spec.rb

User who assigns checker to a review is now saved as a contact person for this assignment.

Add contact person to check assignment

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/check_assignments.coffee
app/assets/stylesheets/application.scss
app/controllers/check_assignments_controller.rb
app/repositories/check_assignments_repository.rb
app/use_cases/check_assignments/set_deadline.rb
app/views/visitors/_last_check_assignments.slim
config/routes.rb
db/migrate/20151127184729_add_deadline_to_check_appointments.rb
db/schema.rb
spec/factories/check_assignment_factory.rb
spec/repositories/check_assignments_repository_spec.rb
spec/use_cases/check_assignments/set_deadline_spec.rb

Allows reviewers to set deadline for their assignments.

Add deadline to assginment

---

app/controllers/projects_controller.rb
app/models/project.rb
app/repositories/projects_repository.rb
app/use_cases/projects/create.rb
app/views/projects/_form.slim
app/views/projects/index.slim
app/views/projects/new.slim
spec/controllers/projects_controller_spec.rb
spec/factories/project_factory.rb
spec/models/project_spec.rb
spec/repositories/projects_repository_spec.rb
spec/use_cases/projects/create_spec.rb

- Allow admins to manually add projects
- Validate project name uniqueness
- Order projects by name by default

Projects: manual creation + some minor updates

---

db/migrate/20151127184729_add_deadline_to_check_appointments.rb
db/migrate/20151127184729_add_deadline_to_check_assignments.rb
spec/use_cases/check_assignments/set_deadline_spec.rb

- Fix broken migration
- Improve specs

Assignment deadline fixes

---

CHANGELOG.md
app/assets/stylesheets/application.scss
app/assets/stylesheets/views/project_checks.scss
app/views/project_checks/index.slim
config/schedule.rb

Trello: https://trello.com/c/mEDhuMfq/206-reminders-app-improvements

Improvements

---

Gemfile
Gemfile.lock
app/controllers/check_assignments_controller.rb
app/controllers/project_checks_controller.rb
app/decorators/check_assignment_decorator.rb
app/decorators/project_decorator.rb
app/models/notifier.rb
app/use_cases/check_assignments/complete.rb
app/use_cases/check_assignments/create.rb
app/use_cases/check_assignments/create_completed.rb
app/use_cases/check_assignments/resolve_action.rb
app/views/check_assignments/complete_check.slim
app/views/checks_history/index.html.slim
app/views/project_checks/index.slim
config/routes.rb
db/migrate/20160418185723_add_note_url_to_check_assignments.rb
db/schema.rb
spec/features/marking_project_as_checked_spec.rb
spec/features/project_check_history_spec.rb
spec/support/pages/reminders/sections/project_checks_history_table.rb
spec/use_cases/check_assignments/complete_spec.rb
spec/use_cases/check_assignments/create_spec.rb
spec/use_cases/check_assignments/notify_spec.rb

thanks to this, it's possible to store review links in reminders app

Add note URL to check assignments

---

app/views/visitors/_last_check_assignments.slim

it should have been part of #30

replace old :post path with a new one

---

CHANGELOG.md
app/controllers/project_checks_controller.rb
app/controllers/project_reminders_matrix_controller.rb
app/controllers/projects_controller.rb
app/decorators/project_check_decorator.rb
app/decorators/project_decorator.rb
app/models/project.rb
app/repositories/project_checks_repository.rb
app/use_cases/projects/unarchive.rb
app/views/layouts/_navigation_links.slim
app/views/project_history/index.slim
app/views/project_reminders_matrix/index.slim
app/views/projects/edit.slim
config/routes.rb
spec/decorators/project_decorator_spec.rb
spec/features/disable_project_spec.rb

New page showing reminders and projects in one table

Project reminders matrix

---

app/controllers/admin/check_assignments_controller.rb
app/decorators/check_assignment_decorator.rb
app/repositories/check_assignments_repository.rb
app/views/admin/check_assignments/_form.slim
app/views/admin/check_assignments/edit.slim
app/views/reports/index.slim
config/routes.rb
spec/repositories/check_assignments_repository_spec.rb

* add buttons for edit and delete
* add view for `check_assignment` so you can fix it when you need

Reports additions

---

app/assets/javascripts/tooltips.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_tooltip.css
app/views/project_checks/index.slim

Just simple tooltip for reminder project info 
https://trello.com/c/UCLrtXBm/47-apka-reminders-pokazywanie-komentarzy-w-widoku-listy-projektow

Tooltip with info for project reminder

---

app/controllers/project_checks_controller.rb
app/controllers/projects_controller.rb
app/jobs/project_checked_on_time_job.rb
app/repositories/project_checks_repository.rb
db/migrate/20170111095444_add_last_check_date_without_disabled_period_and_disabled_date_to_projects_checks.rb
db/schema.rb
spec/jobs/project_checked_on_time_job_spec.rb
spec/repositories/project_checks_repository_spec.rb

When you tun of project by enable on of it should count these days when project was disabled

Stop counting time when project is disabled

---

app/assets/javascripts/application.js
app/views/project_reminders_matrix/index.slim

fix case toggle with turbolinks

fix case toggle with turbolinks

---

.rubocop.yml
CHANGELOG.md
app/controllers/reminders_controller.rb
app/decorators/project_check_decorator.rb
app/decorators/reminder_decorator/base.rb
app/models/notifier.rb
app/use_cases/check_assignments/assign_person.rb
app/use_cases/check_assignments/notify.rb
app/use_cases/project_checks/handle_overdue.rb
app/views/reminders/_form.slim
config/initializers/simple_form_bootstrap.rb
config/locales/en.yml
db/migrate/20170308095511_add_notify_projects_channels_to_reminders.rb
db/schema.rb
spec/decorators/project_check_decorator_spec.rb
spec/models/notifier_spec.rb
spec/use_cases/check_assignments/assign_person_spec.rb
spec/use_cases/check_assignments/complete_spec.rb
spec/use_cases/check_assignments/notify_spec.rb
spec/use_cases/project_checks/handle_notification_day_spec.rb
spec/use_cases/project_checks/handle_overdue_spec.rb

* Ability to set multiple slack channels for Project
* Ability to notify both reminder and project channels
https://netguru.atlassian.net/browse/RD-59

Add ability to notify reminder and project channels.

---

CHANGELOG.md
app/controllers/reminders_controller.rb
app/models/reminder.rb
app/repositories/reminders_repository.rb
app/use_cases/reminders/reorder.rb
app/views/reminders/index.slim
config/routes.rb
db/migrate/20170322153936_add_order_to_reminders.rb
db/schema.rb
spec/factories/reminder_factory.rb
spec/features/reordering_reminders_spec.rb
spec/models/reminder_spec.rb
spec/repositories/reminders_repository_spec.rb
spec/support/pages/reminders/reminders_page.rb
spec/support/pages/reminders/sections/reminder_table_row.rb
spec/use_cases/reminders/reorder_spec.rb

https://netguru.atlassian.net/browse/RD-89
Add an admin interface for reordering reminders

Custom order for reminders

---

app/controllers/reminders_controller.rb
app/decorators/project_check_decorator.rb
app/decorators/reminder_decorator/base.rb
app/decorators/reminder_decorator/form.rb
app/jobs/check_reminder_job.rb
app/jobs/project_checked_on_time_job.rb
app/models/jira.rb
app/models/project_check.rb
app/queries/project_checks/requiring_jira_issues_query.rb
app/use_cases/check_assignments/remind_pending_check_assignment.rb
app/use_cases/project_checks/handle_overdue.rb
app/use_cases/project_checks/override_deadline.rb
app/use_cases/reminders/create.rb
app/use_cases/reminders/update.rb
app/views/reminders/_form.slim
config/locales/en.yml
db/migrate/20170322141648_add_init_columns_to_reminders.rb
db/schema.rb
spec/jobs/check_reminder_job_spec.rb
spec/jobs/project_checked_on_time_job_spec.rb
spec/models/jira_spec.rb
spec/models/notifier_spec.rb
spec/queries/project_checks/requiring_jira_issues_query_spec.rb
spec/repositories/reminders_repository_spec.rb
spec/use_cases/check_assignments/remind_pending_check_assignment_spec.rb
spec/use_cases/project_checks/handle_notification_day_spec.rb
spec/use_cases/project_checks/handle_overdue_spec.rb
spec/use_cases/project_checks/override_deadline_spec.rb

* adds ability to set different valid days for new projects
* adds ability to set different notification days for new projects
https://netguru.atlassian.net/browse/RD-80

New project reminders

---

app/decorators/project_check_decorator.rb
app/jobs/project_checked_on_time_job.rb
app/models/project_check.rb
app/policies/due_date_policy.rb
app/repositories/project_checks_repository.rb
app/use_cases/project_checks/override_deadline.rb
db/migrate/20170329095336_add_started_at_to_project_checks.rb
db/schema.rb
spec/decorators/project_check_decorator_spec.rb
spec/factories/reminder_factory.rb
spec/features/due_dates_spec.rb
spec/jobs/project_checked_on_time_job_spec.rb
spec/policies/due_date_policy_spec.rb
spec/repositories/project_checks_repository_spec.rb
spec/support/pages/reminders/sections/project_checks_table_row.rb
spec/support/shared_contexts/time_frozen.rb
spec/use_cases/project_checks/override_deadline_spec.rb

Restores changes from netguru/reminders#59 after fixing specs

Restore changes from "Stop changing created_at"

---

app/queries/project_checks/requiring_jira_issues_query.rb
spec/queries/project_checks/requiring_jira_issues_query_spec.rb

https://netguru.atlassian.net/browse/RD-117

Update jira issues query after refactor

---

app/assets/javascripts/project_checks.coffee
app/views/project_checks/pick_person.slim

Prevent double click on link to prevent doubled request

prevent duplicated assignment

---

app/models/notifier.rb
config/locales/en.yml
spec/models/notifier_spec.rb
spec/rails_helper.rb

- Allow provide channels in string and array

RD-139 Fix 500 Error

---

config/cronotab.rb

Remove duplicated crono tasks that caused double notifications

Remove duplicated crono tasks

---

app/assets/javascripts/project_checks.coffee
app/views/check_assignments/complete_check.slim
app/views/checks_history/index.html.slim
spec/features/manual_check_spec.rb
spec/features/project_check_history_spec.rb

Make sure that users can mark project as done only when note url is provided.

RMD-5 Disable button when note url is not provided

---

config/locales/en.yml

- Add some example how Jira project key should be implemented

Add more info about Jira project key

---

app/models/notifier.rb
spec/use_cases/check_assignments/notify_spec.rb

Add missing `@result`, it was always `nil`.

Fix notification about Slack channel

---

app/views/reminders/_form.slim

Add `required: false` to the input that's not mandatory.

Add missing required false in form

---

app/models/jira.rb
config/config.yml
spec/models/jira_spec.rb

- Change text of summary
- Add label to created jira issue

[RD-366] Customize creating jira issue
